name: CI

on: [push]

jobs:
  pipeline:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup python
      uses: actions/setup-python@v1 
      with:
        python-version: '3.x'
        architecture: 'x64' 
    - name: Compile
      run: |
        pip3 install -r requirements.txt --upgrade
        python3 mnist_pipeline.py
    - name: Check
      run: |
        ls -lsa
    - name: Get kfplctl
      run: |
        wget https://github.com/TenSt/kubeflow-pipelines-kfplctl/releases/download/v0.0.1/kfplctl
        chmod +x ./kfplctl
    - name: Get all Pipelines
      run: |
        export KUBEFLOW_PIPELINE_API=http://188.40.161.51:8888
        ./kfplctl get pipelines