name: CI

on: [push]

jobs:
  pipeline:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup python
      uses: actions/setup-python@v1 
      with:
        python-version: '3.x'
        architecture: 'x64' 
    - name: Compile
      run: |
        pip3 install -r requirements.txt --upgrade
        python3 mnist_pipeline.py
    - name: Check
      run: |
        ls -lsa
    - name: Get kfplctl
      run: |
        wget https://github.com/TenSt/kubeflow-pipelines-kfplctl/releases/download/v0.0.1/kfplctl
        chmod +x ./kfplctl
    - name: Get all Pipelines
      run: |
        export KUBEFLOW_PIPELINE_API=${{ secrets.KUBEFLOW_PIPELINE_API }}
        ./kfplctl get pipelines
    - name: Upload pipeline
      run: |
        plid="$(./kfplctl upload mnist-pipeline --pipeline mnist_pipeline.py.tar.gz)"
        echo ${plid}
    - name: Create experiment
      run: |
        eid="$(./kfplctl create experiment mnist)"
        echo ${eid}
    - name: Create run
      run: |
        # rid="$(./kfplctl create run mnist --parameters mnistParams.json --pipeline-id $plid --experiment-id $eid)"
        # echo ${rid}
        # troubleshooting
        ./kfplctl create run mnist --parameters mnistParams.json --pipeline-id ${plid} --experiment-id ${eid}
    # - name: Get run status
    #   run: |
    #     ./kfplctl get run $rid status